// 삼양 ShortForm Engine — 확인된 기회 매트릭스
// 방법 1: 데이터 검증된 자산 × 맥락 교차점 (항상 표시)
// 방법 2: AI 추가 발견 (Claude API가 재생성, 하단 표시)

export const confirmedOpportunities = {

  // ═══ 탱글 ═══
  "tgl": [
    {
      asset: "단백질 15g",
      assetIcon: "💪",
      context: "WHO",
      contextDetail: "운동하는 30대 (남성 57%)",
      when: "운동 후 식사 고민",
      keyword: "운동 후 라면",
      volume: 278,
      verified: true,
      pathfinder: "'운동 후 식사추천' → '운동 후 라면' 경로 실제 존재",
      shortformIdea: "PT 트레이너가 추천하는 운동 후 식사 TOP3",
      relatedVolume: { "운동 후 단백질": 2643, "운동 후 식사": 2456 },
    },
    {
      asset: "다이어트 면 대안",
      assetIcon: "🥗",
      context: "PAIN",
      contextDetail: "다이어트 중 면 먹고 싶은 욕구",
      when: "다이어트 중 야식 욕구",
      keyword: "다이어트 중 라면 먹고 싶을때",
      volume: 201,
      verified: true,
      pathfinder: "'다이어트 라면' ClusterFinder에서 '단백질 라면', '건면 다이어트' 키워드 확인",
      shortformIdea: "다이어트 중 면이 먹고 싶을 때, 이걸 먹으면 됩니다",
      relatedVolume: { "다이어트 야식": 6736, "다이어트 간식": 31046, "다이어트 라면": 7203 },
    },
    {
      asset: "병아리콩 건면",
      assetIcon: "🌾",
      context: "NEED",
      contextDetail: "콩담백면보다 나은 대안 탐색",
      when: "다이어트 면 비교할 때",
      keyword: "콩담백면",
      volume: 11156,
      verified: true,
      pathfinder: "'다이어트 면' → '콩담백면' 경로 압도적 — 탱글 부재",
      shortformIdea: "콩담백면만 알고 있다면, 이걸 아직 모르는 겁니다",
      relatedVolume: { "다이어트 면": 1633, "다이어트 파스타": 9180 },
    },
    {
      asset: "4분 간편조리",
      assetIcon: "⏱️",
      context: "WHO",
      contextDetail: "자취 1인가구 여성 (여성 80%, 25-29세 29%)",
      when: "바쁜 평일 저녁",
      keyword: "자취생 간편식",
      volume: 120,
      verified: true,
      shortformIdea: "자취 3년차, 라면으로 단백질 15g 채우는 법",
      relatedVolume: { "혼밥 레시피": 1526, "자취 라면": 129 },
    },
  ],

  // ═══ 맵탱 ═══
  "mep": [
    {
      asset: "캡사이신 효과",
      assetIcon: "🔬",
      context: "INTEREST",
      contextDetail: "스트레스 해소에 관심있는 직장인",
      when: "스트레스 받을 때",
      keyword: "스트레스 풀리는 매운 음식",
      volume: 30,
      verified: true,
      pathfinder: "'스트레스 해소 음식' → '스트레스 풀리는 매운 음식' 경로 실제 존재",
      shortformIdea: "매운 거 먹으면 진짜 스트레스가 풀릴까?",
      relatedVolume: { "스트레스 해소 음식": 300, "매운 음식": 12273 },
    },
    {
      asset: "5가지 매운맛",
      assetIcon: "🌶️",
      context: "PAIN",
      contextDetail: "매운 거 먹고 싶은 욕구 (여성 91%!)",
      when: "매운 거 당길 때",
      keyword: "매운거 먹고 싶을때",
      volume: 118,
      trend: 0.68,
      verified: true,
      shortformIdea: "매운 거 먹고 싶을 때 이거 하나면 됩니다",
      relatedVolume: { "매운 라면 추천": 790, "매운 라면 순위": 4126 },
      demo: "여성 91%, +68% 급성장 — 여성의 매운맛 욕구 폭발 중",
    },
    {
      asset: "5가지 매운맛",
      assetIcon: "🌶️",
      context: "NEED",
      contextDetail: "맵소디(오뚜기) 이탈 소비자",
      when: "매운 라면 비교할 때",
      keyword: "맵소디",
      volume: null,
      verified: true,
      pathfinder: "'맵소디 라면' → '오뚜기 맵소디' → '맵탱' 유입 경로 확인",
      shortformIdea: "맵소디 말고 이거 먹어봤어?",
      relatedVolume: { "매운 라면 추천": 790 },
    },
    {
      asset: "챌린지 콘텐츠",
      assetIcon: "🎬",
      context: "INTEREST",
      contextDetail: "먹방/챌린지 시청자",
      when: "숏폼 소비 시간",
      keyword: "매운맛 챌린지",
      volume: 162,
      verified: true,
      shortformIdea: "매운맛 5단계, 어디까지 가능해?",
      relatedVolume: { "먹방": 2787350 },
    },
  ],

  // ═══ 삼양1963 ═══
  "1963": [
    {
      asset: "우지파동 스토리",
      assetIcon: "📖",
      context: "INTEREST",
      contextDetail: "역사/비하인드 스토리 관심층",
      when: "새로운 사실을 알았을 때",
      keyword: "우지라면",
      volume: 49006,
      verified: true,
      shortformIdea: "우지파동의 진실, 아직도 모르는 사람이 많습니다",
      relatedVolume: {},
      demo: "브랜드명(9,140회)보다 5배 큰 검색 = 스토리가 최강의 콘텐츠 자산",
    },
    {
      asset: "야식/혼밥 대표",
      assetIcon: "🌙",
      context: "WHEN",
      contextDetail: "밤에 배고플 때, 다이어트 중 야식 욕구",
      when: "야식 시간 (밤 9-12시)",
      keyword: "다이어트 야식",
      volume: 6736,
      verified: true,
      shortformIdea: "다이어트 중인데 야식이 먹고 싶다면",
      relatedVolume: { "야식 추천": 21856, "야식 라면": 1473 },
      demo: "여성 73%, 30대 39% — 야식 욕구는 다이어트와 공존",
    },
    {
      asset: "라면 레시피",
      assetIcon: "👨‍🍳",
      context: "WHEN",
      contextDetail: "주말 요리할 때",
      when: "주말 여유 시간",
      keyword: "주말 요리",
      volume: 1286,
      verified: true,
      shortformIdea: "주말에 라면 한 그릇, 이렇게 끓이면 레스토랑급",
      relatedVolume: { "라면 레시피": 20300, "라면 맛있게 끓이는 법": 3173 },
      demo: "여성 73%, 40대 45% — 주말 요리 관심층은 40대 여성 중심",
    },
    {
      asset: "프리미엄 원조",
      assetIcon: "👑",
      context: "WHERE",
      contextDetail: "라면 맛집/프리미엄 라면 비교",
      when: "라면 선택할 때",
      keyword: "프리미엄 라면",
      volume: 406,
      verified: true,
      pathfinder: "'프리미엄 라면' 검색 시 장인라면/더미식으로 흐름 — 삼양1963 부재",
      shortformIdea: "프리미엄 라면 TOP3, 1위가 의외입니다",
      relatedVolume: { "라면 추천": 10866, "라면 순위": 6606 },
    },
  ],

  // ═══ 펄스랩 ═══
  "pls": [
    {
      asset: "단백질 47g",
      assetIcon: "💪",
      context: "WHO",
      contextDetail: "운동하는 사람 (운동 후 단백질 검색 여성 54%)",
      when: "운동 후 간식 고민",
      keyword: "운동 후 단백질",
      volume: 2643,
      verified: true,
      shortformIdea: "운동 끝나고 단백질 47g 채우는 의외의 간식",
      relatedVolume: { "운동 후 간식": 183, "단백질 간식": 4703 },
    },
    {
      asset: "길트프리 스낵",
      assetIcon: "✨",
      context: "WHERE",
      contextDetail: "사무실/회사 (여성 85%, 25-29세 25%)",
      when: "오후 3시 간식 타임",
      keyword: "회사 간식 추천",
      volume: 1720,
      trend: 0.15,
      verified: true,
      shortformIdea: "회사에서 몰래 먹는 죄책감 없는 간식",
      relatedVolume: { "사무실 간식": 11453 },
      demo: "여성 85%, CPC $2.42 — B2B 간식 납품까지 연결 가능한 고가치 키워드",
    },
    {
      asset: "병아리콩 + 캐슈넛",
      assetIcon: "🌾",
      context: "INTEREST",
      contextDetail: "건강/영양에 관심 있는 30대 여성",
      when: "건강 정보 탐색할 때",
      keyword: "병아리콩 효능",
      volume: 29180,
      verified: true,
      shortformIdea: "병아리콩이 이렇게 좋은 줄 몰랐습니다",
      relatedVolume: { "병아리콩": 59813, "캐슈넛 효능": 16060 },
    },
    {
      asset: "후무스",
      assetIcon: "🥙",
      context: "NEED",
      contextDetail: "후무스를 이미 알고/만들고 싶은 사람",
      when: "레시피 탐색할 때",
      keyword: "후무스 만들기",
      volume: 8363,
      verified: true,
      shortformIdea: "후무스 만들기 귀찮으면, 이게 있습니다",
      relatedVolume: { "후무스": 22196 },
    },
    {
      asset: "식물성 단백질",
      assetIcon: "🌱",
      context: "INTEREST",
      contextDetail: "비건/식물성에 관심 있는 사람",
      when: "단백질 비교할 때",
      keyword: "식물성 단백질",
      volume: 7230,
      verified: true,
      pathfinder: "'식물성 단백질' → '흡수율' → '유청 단백질' 비교 경로",
      shortformIdea: "식물성 vs 동물성 단백질, 뭐가 다를까?",
      relatedVolume: { "비건 간식": 436 },
    },
  ],
};

// ═══ 앱에서의 동작 ═══
// [확인된 기회] — confirmedOpportunities에서 해당 brand 필터 → 항상 표시
//   각 기회: 자산 아이콘 + 자산명 × 맥락(WHO/WHEN/WHERE/PAIN/NEED/INTEREST)
//   검색량 + PathFinder 경로 + 숏폼 아이디어 예시
//   "✅ 데이터 검증" 배지
//
// [AI 추가 발견] — Claude API가 confirmedOpportunities를 참고하되 새로운 교차점 제안
//   프롬프트: "확인된 기회 외에 이 자산과 키워드 풀에서 새로운 맥락 교차점을 찾아"
//   "🤖 AI 발견" 배지 + 재생성 가능
